# Generated by Django 6.0 on 2025-12-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('county', models.CharField(max_length=100)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkt.make')),
            ],
        ),
    ]
