# Generated by Django 6.0 on 2025-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='make/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
